version: '3'
services:
  web:
    image: nginx:latest
    env_file: .env.mysql
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    build:
      context: ./
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  mysql:
    image: mariadb:latest
    env_file: .env.mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
volumes:
  mysqldata: {}
