USE survey;

CREATE TABLE demo (
	ID INT AUTO_INCREMENT,
	LASTNAME VARCHAR(255) NOT NULL,
	FIRSTNAME VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

SHOW TABLES;
DESCRIBE demo;

INSERT INTO demo (LASTNAME, FIRSTNAME) VALUES ('Mustermann', 'Max');
SELECT * FROM demo;

INSERT INTO demo (LASTNAME, FIRSTNAME) VALUES ('Musterfrau', 'Maxi');
SELECT * FROM demo;
